version: '3'

services:
  node0:
    container_name: n0
    image: "anrg/swarmdag"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build:/fakego/src/github.com/ANRGUSC/swarmdag/build:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: n1
    image: "anrg/swarmdag"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./build:/fakego/src/github.com/ANRGUSC/swarmdag/build:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: n2
    image: "anrg/swarmdag"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fakego/src/github.com/ANRGUSC/swarmdag/build:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: n3
    image: "anrg/swarmdag"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fakego/src/github.com/ANRGUSC/swarmdag/build:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
